In [1]:
# import numpy
import numpy as np

In [2]:
# generate 'ground truth'
y_true = np.random.normal(0,1,10)

# generate random errors
errors = np.random.normal(0,0.02,10)

# simulate predictions
y_pred = y_true + errors

In [3]:
y_true, errors, y_pred

(array([ 0.06397172,  0.72636435, -0.65583266,  0.02925462, -1.55729656,
         1.6685137 , -0.05067663, -0.31035122,  1.20627849, -0.7628808 ]),
 array([ 0.02051722, -0.01430849,  0.00706663, -0.0317399 ,  0.01164857,
         0.00374171, -0.01178554,  0.01807039,  0.0305448 ,  0.01613408]),
 array([ 0.08448894,  0.71205586, -0.64876602, -0.00248528, -1.54564799,
         1.67225541, -0.06246218, -0.29228082,  1.23682329, -0.74674672]))

In [4]:
# import MSE from sklearn
from sklearn.metrics import mean_squared_error

# compute MSE
MSE = mean_squared_error(y_true,y_pred)  

# print MSE
print(MSE)

0.0003491469217498967


In [5]:
# RMSE by Numpy
RMSE = np.sqrt(MSE)
print(RMSE)

# RMSE by sklearn
RMSE = mean_squared_error(y_true,y_pred,squared=False)
print(RMSE)

0.018685473548987103
0.018685473548987103


In [6]:
# ground truth
y_true = [1,1,0,1,0,0,1,0,0,1]

# simulate probabilites of positive class
y_proba = [0.9,0.7,0.2,0.99,0.7,0.1,0.5,0.2,0.4,0.6]

# set the threshold to predict positive class
thres = 0.5

# class predictions
y_pred = [int(value > thres) for value in y_proba]

In [7]:
y_pred

[1, 1, 0, 1, 1, 0, 0, 0, 0, 1]

In [8]:
# import accuracy_score from sklearn
from sklearn.metrics import accuracy_score

# compute accuracy
accuracy = accuracy_score(y_true,y_pred)

# print accuracy
print(accuracy)

0.8


In [9]:
# import f1_score from sklearn
from sklearn.metrics import f1_score

# compute F1-score
f1_score = f1_score(y_true,y_pred)

# print F1-score
print(f1_score)

0.8000000000000002


In [10]:
# import roc_auc_score from sklearn
from sklearn.metrics import roc_auc_score

# compute AUC-score
auc = roc_auc_score(y_true,y_proba)

# print AUC-score
print(auc)


0.9
